*&---------------------------------------------------------------------*
*& Report ZPRASAD_ASSIGNMENT_04_30
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZPRASAD_ASSIGNMENT_04_30 NO STANDARD PAGE HEADING LINE-COUNT 20(3) LINE-SIZE 500 MESSAGE-ID ZPRASAD_UST_MSG.




types : BEGIN OF  LS_TAB,
    SID TYPE ZPRASADSTU_ID,
  SNAME TYPE zprasadstU_name,
  SMOBILE TYPE ZPRASADSTU_MOBILE,
  CID TYPE ZPRASADCOURSE_ID,
  CNAME TYPE ZPRASADCOURSE_NAME,
  END OF LS_TAB.

  DATA : LT_TAB TYPE STANDARD TABLE OF LS_TAB,
        WA_TAB TYPE LS_TAB,
        LV_ID TYPE ZPRASADSTU_ID,
        LV_COUNT TYPE I.

  SELECT-OPTIONS S_ID FOR LV_ID OBLIGATORY.
  INITIALIZATION.
CLEAR : LT_TAB,WA_TAB.
S_ID-LOW = '101'.
S_ID-HIGH = '109'.
APPEND S_ID.

  AT SELECTION-SCREEN.
    SELECT SINGLE STU_ID
      into s_id from zprasad_student
      where stu_id in s_id.

      IF SY-SUBRC EQ 0.
    MESSAGE S000.
  ELSE.
    MESSAGE W002.
    ENDIF.

START-OF-SELECTION.
  PERFORM DATABASEVIEW_JOIN.
END-OF-SELECTION.

  PERFORM PRINTING_FROM_WA_TAB.
  LV_COUNT = SY-LINCT - SY-LINNO.
SKIP LV_COUNT.

TOP-OF-PAGE.
ULINE.
WRITE : /'STUDENT ID' , 20 'STUDENT NAME',40 'STUDENT MOBILE',60 'STUDENT COURSE ID',90'STUDENT COURSE NAME' .ULINE.


END-OF-PAGE.
WRITE : 'CURRENT PAGE ',SY-LINCT,'CURRENT DATE ',SY-DATUM.






FORM databaseview_join .
  SELECT STU_ID STU_NAME STU_MOBILE COURSE_ID COURSE_NAME
    INTO TABLE LT_TAB
    FROM ZPRASAD_DBVIEW1
    WHERE STU_ID BETWEEN S_ID-LOW AND S_ID-HIGH.
ENDFORM.

FORM printing_from_wa_tab .
LOOP AT LT_TAB INTO WA_TAB.
      WRITE : /
      WA_TAB-SID,20 WA_TAB-SNAME,40 WA_TAB-SMOBILE,60 WA_TAB-CID, 90 WA_TAB-CNAME.
      ENDLOOP.
ENDFORM.